<a href="https://colab.research.google.com/github/augustine-uba1/tensorFlow/blob/main/TensorFlows.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [3]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [11]:
# CREATING A ONE DIMENSIONAL TENSOR
tensor_one_d = tf.constant([2,8,-9, 25, 50.2])
print(tensor_one_d)

tf.Tensor([ 2.   8.  -9.  25.  50.2], shape=(5,), dtype=float32)
tf.Tensor(
[[4 5 8]
 [5 9 9]
 [5 6 9]
 [4 5 6]], shape=(4, 3), dtype=int32)


In [17]:
# CREATING A 2 DIMENSIONAL TENSOR
tensor_two_d = tf.constant([
    [4,5,8],
    [5,9,9],
    [5,6,9],
    [4,5,6]
], dtype=tf.float16)
print(tensor_two_d)

tf.Tensor(
[[4. 5. 8.]
 [5. 9. 9.]
 [5. 6. 9.]
 [4. 5. 6.]], shape=(4, 3), dtype=float16)


In [15]:
# CREATING A 3 DIMENSIONAL TENSOR
tensor_three_d = tf.constant([
    [[4,5,8],
    [5,9,9],],

    [[4,5,8],
    [5,9,9],],

    [[4,5,8],
    [5,9,9],],

    [[4,5,8],
    [5,9,9],]
])
tensor_shape = tensor_three_d.shape
print(tensor_shape)
tensor_dimension = tensor_three_d.ndim
print(tensor_dimension)
print(tensor_three_d)

(4, 2, 3)
3
tf.Tensor(
[[[4 5 8]
  [5 9 9]]

 [[4 5 8]
  [5 9 9]]

 [[4 5 8]
  [5 9 9]]

 [[4 5 8]
  [5 9 9]]], shape=(4, 2, 3), dtype=int32)


In [16]:
# CREATING A FOUR DIMENSIONAL TENSOR
tensor_four_d = tf.constant( [
    [[[7,5,8],
    [8,0,9],],

    [[4,5,8],
    [5,9,9],],

    [[1,5,8],
    [5,9,9],],

    [[4,5,8],
    [5,9,9],]],

    [[[60,53,8],
    [5,99,78],],

    [[49,75,8],
    [56,95,9],],

    [[4,5,8],
    [5,9,9],],

    [[4,5,8],
    [5,9,9],]],

    [[[4,5,68],
    [5,69,59],],

    [[45,5,83],
    [5,9,9],],

    [[46,55,8],
    [56,96,92],],

    [[48,5,8],
    [5,9,9],]]
])

print (tensor_four_d.shape)

(3, 4, 2, 3)


In [21]:
# USING CASTING
tensor_one_d_before_casting = tf.constant([2,8,-9, 25, 50.2], dtype=tf.float16)
casted_tensor_one_d = tf.cast(tensor_one_d_before_casting, dtype=tf.bool)
print(tensor_one_d_before_casting)
print(casted_tensor_one_d)

tf.Tensor([ 2.   8.  -9.  25.  50.2], shape=(5,), dtype=float16)
tf.Tensor([ True  True  True  True  True], shape=(5,), dtype=bool)
